//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbAfrzEntities : DbContext
    {
        public dbAfrzEntities()
            : base("name=dbAfrzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tabBanks> tabBanks { get; set; }
        public virtual DbSet<tabBuyRequestItems> tabBuyRequestItems { get; set; }
        public virtual DbSet<tabBuyRequests> tabBuyRequests { get; set; }
        public virtual DbSet<tabCategories> tabCategories { get; set; }
        public virtual DbSet<tabCoInformation> tabCoInformation { get; set; }
        public virtual DbSet<tabCompanies> tabCompanies { get; set; }
        public virtual DbSet<tabCurrentAffairs> tabCurrentAffairs { get; set; }
        public virtual DbSet<tabDepartments> tabDepartments { get; set; }
        public virtual DbSet<tabEmployees> tabEmployees { get; set; }
        public virtual DbSet<tabEmployeesBankInfo> tabEmployeesBankInfo { get; set; }
        public virtual DbSet<tabEquipName> tabEquipName { get; set; }
        public virtual DbSet<tabEquipSamples> tabEquipSamples { get; set; }
        public virtual DbSet<tabFamSettings> tabFamSettings { get; set; }
        public virtual DbSet<tabInvoiceItems> tabInvoiceItems { get; set; }
        public virtual DbSet<tabInvoices> tabInvoices { get; set; }
        public virtual DbSet<tabLoadingLadles> tabLoadingLadles { get; set; }
        public virtual DbSet<tabLocationes> tabLocationes { get; set; }
        public virtual DbSet<tabMaintenanceFurnaceEquips> tabMaintenanceFurnaceEquips { get; set; }
        public virtual DbSet<tabMaintenanceItems> tabMaintenanceItems { get; set; }
        public virtual DbSet<tabMaintenanceParts> tabMaintenanceParts { get; set; }
        public virtual DbSet<tabMaintenances> tabMaintenances { get; set; }
        public virtual DbSet<tabMeasurementUnits> tabMeasurementUnits { get; set; }
        public virtual DbSet<tabMenus> tabMenus { get; set; }
        public virtual DbSet<tabMenusEmployees> tabMenusEmployees { get; set; }
        public virtual DbSet<tabPartBranch> tabPartBranch { get; set; }
        public virtual DbSet<tabPartName> tabPartName { get; set; }
        public virtual DbSet<tabPartSamples> tabPartSamples { get; set; }
        public virtual DbSet<tabPartSubBranch> tabPartSubBranch { get; set; }
        public virtual DbSet<tabPartTypes> tabPartTypes { get; set; }
        public virtual DbSet<tabPosts> tabPosts { get; set; }
        public virtual DbSet<tabProductionMeltLoadings> tabProductionMeltLoadings { get; set; }
        public virtual DbSet<tabProjects> tabProjects { get; set; }
        public virtual DbSet<tabProperties> tabProperties { get; set; }
        public virtual DbSet<tabProvinces> tabProvinces { get; set; }
        public virtual DbSet<tabShifts> tabShifts { get; set; }
        public virtual DbSet<tabShiftType> tabShiftType { get; set; }
        public virtual DbSet<tabStoreGetOutItems> tabStoreGetOutItems { get; set; }
        public virtual DbSet<tabStoreGetOuts> tabStoreGetOuts { get; set; }
        public virtual DbSet<tabStores> tabStores { get; set; }
        public virtual DbSet<tabStuffMaterials> tabStuffMaterials { get; set; }
        public virtual DbSet<tabStuffProperties> tabStuffProperties { get; set; }
        public virtual DbSet<tabStuffSections> tabStuffSections { get; set; }
        public virtual DbSet<tabStuffTypes> tabStuffTypes { get; set; }
        public virtual DbSet<tabSubDepartments> tabSubDepartments { get; set; }
        public virtual DbSet<tabSubdepartmentSubsets> tabSubdepartmentSubsets { get; set; }
        public virtual DbSet<tabSubProjects> tabSubProjects { get; set; }
        public virtual DbSet<tabSubZones> tabSubZones { get; set; }
        public virtual DbSet<tabTagParts> tabTagParts { get; set; }
        public virtual DbSet<tabTechnicalDocumentItems> tabTechnicalDocumentItems { get; set; }
        public virtual DbSet<tabTechnicalDocuments> tabTechnicalDocuments { get; set; }
        public virtual DbSet<tabTechnicalDocumentTypes> tabTechnicalDocumentTypes { get; set; }
        public virtual DbSet<tabUsers> tabUsers { get; set; }
        public virtual DbSet<tabVendors> tabVendors { get; set; }
        public virtual DbSet<tabZones> tabZones { get; set; }
    }
}
