//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabCoInformation
    {
        public int intID { get; set; }
        public string nvcName { get; set; }
        public string nvcCoType { get; set; }
        public Nullable<System.DateTime> datRegister { get; set; }
        public string nvcRegisterCode { get; set; }
        public string nvcCoID { get; set; }
        public string nvcAddress { get; set; }
        public string nvcPostalCode { get; set; }
        public string nvcTell { get; set; }
        public string nvcFax { get; set; }
        public string nvcTaxID { get; set; }
        public string nvcProvince { get; set; }
        public string nvcCity { get; set; }
        public string nvcWebSite { get; set; }
    }
}
