//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabEmployees
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public string nvcCoID { get; set; }
        public string nvcFirstname { get; set; }
        public string nvcLastname { get; set; }
        public string nvcNationalID { get; set; }
        public string nvcInsuranceNumber { get; set; }
        public Nullable<int> intDepartment { get; set; }
        public Nullable<int> intSubDepartment { get; set; }
        public Nullable<int> intSubDepartmentSubset { get; set; }
        public Nullable<int> intWorkGroup { get; set; }
        public Nullable<bool> bitIsLeader { get; set; }
        public Nullable<int> intPost { get; set; }
        public Nullable<int> intEmploymentType { get; set; }
        public Nullable<bool> bitIsShiftMode { get; set; }
        public Nullable<int> intShiftType { get; set; }
        public string nvcMobileNumber { get; set; }
        public Nullable<System.DateTime> datBirth { get; set; }
        public string nvcFatherName { get; set; }
        public Nullable<int> intEducationLevel { get; set; }
        public string nvcLocationProvince { get; set; }
        public string nvcLocationCounty { get; set; }
        public string nvcLocationCityVillage { get; set; }
        public string nvcLocationAddress { get; set; }
        public string nvcPostalCode { get; set; }
    
        public virtual tabDepartments tabDepartments { get; set; }
        public virtual tabSubDepartments tabSubDepartments { get; set; }
        public virtual tabSubdepartmentSubsets tabSubdepartmentSubsets { get; set; }
    }
}
