//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabEquipSamples
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public Nullable<int> intCompany { get; set; }
        public Nullable<int> intLocation { get; set; }
        public int intZone { get; set; }
        public int intSubZone { get; set; }
        public int intCategory { get; set; }
        public int intEquipName { get; set; }
        public Nullable<int> intOrder { get; set; }
    
        public virtual tabCategories tabCategories { get; set; }
        public virtual tabCompanies tabCompanies { get; set; }
        public virtual tabEquipName tabEquipName { get; set; }
        public virtual tabSubZones tabSubZones { get; set; }
        public virtual tabZones tabZones { get; set; }
        public virtual tabLocationes tabLocationes { get; set; }
    }
}
