//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabEmployeesBankInfo
    {
        public int intID { get; set; }
        public string nvcCoID { get; set; }
        public string nvcName { get; set; }
        public string nvcAccount { get; set; }
        public string nvcShaba { get; set; }
        public string nvcAtmCard { get; set; }
    }
}
