//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabFamSettings
    {
        public short intID { get; set; }
        public Nullable<int> intMaintenanceFurnaceShifttype { get; set; }
        public Nullable<System.DateTime> datMaintenanceFurnaceDateOrgin { get; set; }
        public Nullable<int> intProductionFurnaceShifttype { get; set; }
        public Nullable<System.DateTime> datProductionFurnaceDateOrgin { get; set; }
        public string nvcEquipPicsPath { get; set; }
        public string nvcInvoiceImagesPath { get; set; }
        public Nullable<byte> tinTapholeCount { get; set; }
        public Nullable<byte> tinLadleCount { get; set; }
        public string nvcLoadingSerialPortRS232 { get; set; }
    }
}
