//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabLoadingLadles
    {
        public short intID { get; set; }
        public string nvcNumber { get; set; }
        public Nullable<byte> intLoadingCount { get; set; }
        public Nullable<int> intEmptyWeight { get; set; }
        public Nullable<bool> bitIsCurrent { get; set; }
        public Nullable<int> intServiceCount { get; set; }
    }
}
