//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabMaintenances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabMaintenances()
        {
            this.tabMaintenanceItems = new HashSet<tabMaintenanceItems>();
        }
    
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public System.DateTime datWorkGroup { get; set; }
        public int intDepartment { get; set; }
        public int intSubDepartment { get; set; }
        public int intWourkGroup { get; set; }
        public int intShift { get; set; }
        public string nvcCoIdsWorkGroup { get; set; }
        public string nvcCoIdLeader { get; set; }
    
        public virtual tabDepartments tabDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabMaintenanceItems> tabMaintenanceItems { get; set; }
        public virtual tabShifts tabShifts { get; set; }
        public virtual tabSubDepartments tabSubDepartments { get; set; }
    }
}
