//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabMaintenanceParts
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public int intMaintenanceItem { get; set; }
        public string nvcPart { get; set; }
        public int intMaintenaceType { get; set; }
        public double intCount { get; set; }
    
        public virtual tabMaintenanceItems tabMaintenanceItems { get; set; }
    }
}
