//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabMaintenanceItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabMaintenanceItems()
        {
            this.tabMaintenanceParts = new HashSet<tabMaintenanceParts>();
        }
    
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public int intMaintenance { get; set; }
        public System.TimeSpan timItem { get; set; }
        public string nvcCoIdsWorker { get; set; }
        public int intDuration { get; set; }
        public string nvcEquip { get; set; }
        public int intMaintenanceType { get; set; }
        public bool bitIsDueToShutDown { get; set; }
        public bool bitIsNeedToShutDown { get; set; }
        public bool bitIsSuccessful { get; set; }
        public string nvcTips { get; set; }
    
        public virtual tabMaintenances tabMaintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabMaintenanceParts> tabMaintenanceParts { get; set; }
    }
}
