//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabPartTypes
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public int intStore { get; set; }
        public int intCategory { get; set; }
        public int intName { get; set; }
        public int intBranch { get; set; }
        public int intSubBranch { get; set; }
        public int intMeasurementUnit { get; set; }
        public string nvcProperties { get; set; }
        public Nullable<double> floOrderPoint { get; set; }
        public Nullable<double> floSupply { get; set; }
    
        public virtual tabCategories tabCategories { get; set; }
        public virtual tabMeasurementUnits tabMeasurementUnits { get; set; }
        public virtual tabPartName tabPartName { get; set; }
        public virtual tabPartBranch tabPartBranch { get; set; }
        public virtual tabPartSubBranch tabPartSubBranch { get; set; }
        public virtual tabStores tabStores { get; set; }
    }
}
