//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabProductionMeltLoadings
    {
        public int intID { get; set; }
        public Nullable<int> intLoadingCount { get; set; }
        public Nullable<System.DateTime> datDate { get; set; }
        public Nullable<System.TimeSpan> timStart { get; set; }
        public Nullable<System.TimeSpan> timStop { get; set; }
        public string nvcLadleNumber { get; set; }
        public Nullable<int> intLadleLoadingCount { get; set; }
        public Nullable<int> intEmptyWeight { get; set; }
        public Nullable<int> intFillWeight { get; set; }
        public Nullable<int> intMasidegiWeight { get; set; }
        public string nvcTapholeNumber { get; set; }
        public Nullable<byte> intTapholePosition { get; set; }
        public string nvcGroupNumber { get; set; }
        public Nullable<byte> intShift { get; set; }
    }
}
