//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabProperties
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public string nvcName { get; set; }
        public int intNumber { get; set; }
        public int intMeasurementUnit { get; set; }
        public int intCategory { get; set; }
    
        public virtual tabCategories tabCategories { get; set; }
        public virtual tabMeasurementUnits tabMeasurementUnits { get; set; }
    }
}
