//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabRequests
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public Nullable<int> intNumber { get; set; }
        public Nullable<int> intDepartment { get; set; }
        public Nullable<int> intRowBudget { get; set; }
        public Nullable<System.DateTime> datDate { get; set; }
        public string nvcRequesterCoID { get; set; }
        public string nvcSupervisorCoID { get; set; }
        public string nvcPlantmanagerCoID { get; set; }
        public string nvcCeoCoID { get; set; }
    }
}
