//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabRequestItems
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public Nullable<int> intRequestNumber { get; set; }
        public string nvcStoreCode { get; set; }
        public Nullable<double> floAmount { get; set; }
    }
}
