//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabSubProjects
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public int intCategory { get; set; }
        public int intProject { get; set; }
        public string nvcName { get; set; }
        public System.DateTime datStart { get; set; }
        public int intDuration { get; set; }
        public int intProgress { get; set; }
        public string nvcTip { get; set; }
        public Nullable<int> intWeight { get; set; }
    
        public virtual tabCategories tabCategories { get; set; }
        public virtual tabProjects tabProjects { get; set; }
    }
}
