//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabShiftType
    {
        public short intID { get; set; }
        public Nullable<int> intNumber { get; set; }
        public string nvcName { get; set; }
        public Nullable<byte> intShiftsCountInDay { get; set; }
        public Nullable<byte> intWorkShiftsRepeatCount { get; set; }
        public Nullable<byte> intRestShiftRepeatCount { get; set; }
        public Nullable<System.TimeSpan> timShiftStartTime1 { get; set; }
        public Nullable<System.TimeSpan> timShiftStartTime2 { get; set; }
        public Nullable<System.TimeSpan> timShiftStartTime3 { get; set; }
    }
}
