//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabSubprojects
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public Nullable<int> intCategory { get; set; }
        public Nullable<int> intProjectNumber { get; set; }
        public string nvcName { get; set; }
        public Nullable<System.DateTime> datStart { get; set; }
        public Nullable<int> intDuration { get; set; }
        public Nullable<int> intProgress { get; set; }
        public string nvcTip { get; set; }
    }
}
