//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabStoreGetOutItems
    {
        public int intID { get; set; }
        public bool bitSelect { get; set; }
        public int intStoreGetOutNumber { get; set; }
        public string nvcStuffStoreCode { get; set; }
        public double floStuffAmount { get; set; }
        public string nvcEquipTag { get; set; }
        public int intTechnicalActionType { get; set; }
    }
}
