//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabStoreGetOuts
    {
        public int intID { get; set; }
        public bool bitSelect { get; set; }
        public int intNumber { get; set; }
        public int intDepartment { get; set; }
        public int intSubDepartment { get; set; }
        public System.DateTime datDate { get; set; }
        public int intGroupNumber { get; set; }
        public string nvcRequesterCoID { get; set; }
        public string nvcDepartmentSupervisorCoID { get; set; }
    }
}
