//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabStuffTypes
    {
        public int intID { get; set; }
        public string nvcStore { get; set; }
        public string nvcSection { get; set; }
        public string nvcMaterial { get; set; }
        public string nvcName { get; set; }
        public string nvcCode { get; set; }
    }
}
