//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabTechnicalDocumentItems
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public string nvcDocumentCode { get; set; }
        public string nvcEquipCode { get; set; }
        public string nvcPartCode { get; set; }
        public Nullable<bool> bitIsMain { get; set; }
    }
}
