//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabTechnicalDocuments
    {
        public short intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public Nullable<int> intCategory { get; set; }
        public string nvcZone { get; set; }
        public string nvcCode { get; set; }
        public string nvcCoDesigner { get; set; }
        public string nvcPersonDesigner { get; set; }
        public string nvcRevisionNumber { get; set; }
        public string nvcTip { get; set; }
    }
}
