//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabTechnicalDocumentTags
    {
        public short intID { get; set; }
        public string nvcDocumentCode { get; set; }
        public string nvcPartTag { get; set; }
        public string nvcTip { get; set; }
    }
}
