//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabUsers
    {
        public int intID { get; set; }
        public string nvcUsername { get; set; }
        public string nvcPassword { get; set; }
        public string nvcCoID { get; set; }
        public Nullable<bool> bitLogined { get; set; }
        public Nullable<bool> bitOfficeEnabed { get; set; }
        public Nullable<bool> bitFinanceEnabed { get; set; }
        public Nullable<bool> bitCommerceEnabed { get; set; }
        public Nullable<bool> bitProductionEnabed { get; set; }
        public Nullable<bool> bitTechnicalEnabed { get; set; }
        public Nullable<bool> bitStoreEnabed { get; set; }
        public Nullable<bool> bitLabEnabed { get; set; }
    }
}
