//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baran.Ferroalloy.Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabVendors
    {
        public int intID { get; set; }
        public Nullable<bool> bitSelect { get; set; }
        public Nullable<int> intNumber { get; set; }
        public Nullable<int> intCategory { get; set; }
        public string nvcBrand { get; set; }
        public string nvcActivityType { get; set; }
        public string nvcActivities { get; set; }
        public string nvcTell { get; set; }
        public string nvcFirstName { get; set; }
        public string nvcLastName { get; set; }
        public string nvcCity { get; set; }
        public string nvcAddress { get; set; }
    }
}
